version: '3'

services:
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    restart: always
    ports:
      - 5010:80
    networks:
      - app_network

  landing:
    container_name: landing
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    restart: always
    ports:
      - 5020:5020
    networks:
      - app_network

  maruhachi:
    container_name: maruhachi
    build:
      context: .
      dockerfile: ./apps/maruhachi/Dockerfile
    restart: always
    ports:
      - 5030:5030
    networks:
      - app_network

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./Dockerfile.docs
    restart: always
    ports:
      - 5040:5040
    networks:
      - app_network

networks:
  app_network:
    external: true
