FROM node:18-alpine AS builder

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

COPY . .

RUN yarn global add turbo

COPY package.json yarn.lock ./

RUN yarn install

RUN yarn storybook:build

RUN yarn storybook:move

FROM nginx:1.21-alpine AS production

ENV NODE_ENV production

RUN rm -rf /usr/share/nginx/app-storybook/* && rm -rf /docker-entrypoint.d/*

COPY --from=builder /app/storybook-static /usr/share/nginx/app-storybook

EXPOSE 5040

CMD ["nginx", "-g", "daemon off;"]
