import { pathIcons } from '../../assets/icons';
import { IconUtils } from './utils';

export const IconsSortMock = {
  notifications: [
    'NotificationUnreadIcon',
    'NotificationUnreadLinesIcon',
    'NotificationRemoveIcon',
    'NotificationRemoveLinesIcon',
    'NotificationBellIcon',
    'NotificationBellBingIcon',
    'NotificationBellOffIcon'
  ],
  noteDocuments: [
    'DocumentIcon',
    'DocumentTextIcon',
    'DocumentAddIcon',
    'DocumentMedicineIcon',
    'DocumentsIcon',
    'DocumentMinimalisticIcon',
    'NoteMinimalisticIcon',
    'NotesIcon',
    'ClipboardIcon',
    'ClipboardListIcon',
    'ClipboardTextIcon',
    'ClipboardHeartIcon',
    'ClipboardRemoveIcon',
    'ClipboardAddIcon',
    'ClipboardCheckIcon',
    'NoteBookIcon',
    'ArchiveDownMinimalisticIcon',
    'ArchiveUpMinimalisticIcon',
    'ArchiveMinimalisticIcon',
    'ArchiveDownIcon',
    'ArchiveUpIcon',
    'ArchiveCheckIcon',
    'ArchiveIcon'
  ],
  arrowActions: [
    'SendSquareIcon',
    'ReceiveSquareIcon',
    'UploadSquareIcon',
    'DownloadSquareIcon',
    'SendTwiceSquareIcon',
    'ReceiveTwiceSquareIcon',
    'UploadTwiceSquareIcon',
    'DownloadTwiceSquareIcon',
    'UndoLeftRoundIcon',
    'UndoRightRoundIcon',
    'UndoLeftIcon',
    'UndoRightIcon',
    'UndoLeftRoundSquareIcon',
    'UndoRightRoundSquareIcon',
    'UndoLeftSquareIcon',
    'UndoRightSquareIcon',
    'SquareBottomUpIcon',
    'SquareBottomDownIcon',
    'SquareTopUpIcon',
    'SquareTopDownIcon',
    'CircleBottomUpIcon',
    'CircleBottomDownIcon',
    'CircleTopDownIcon',
    'CircleTopUpIcon',
    'ScaleIcon',
    'ReorderIcon',
    'MinimizeIcon',
    'MaximizeIcon',
    'MaximizeSquareIcon',
    'MaximizeSquareMinimalisticIcon',
    'MinimizeSquareIcon',
    'MinimizeSquareMinimalisticIcon',
    'MaximizeSquare2Icon',
    'MinimizeSquare2Icon',
    'MaximizeSquare3Icon',
    'MinimizeSquare3Icon',
    'LogoutIcon',
    'LoginIcon',
    'ImportIcon',
    'ExportIcon',
    'Logout2Icon',
    'Login2Icon',
    'UploadIcon',
    'DownloadIcon',
    'UploadMinimalisticIcon',
    'DownloadMinimalisticIcon',
    'Login3Icon',
    'Logout3Icon',
    'ExitIcon',
    'ScreenShareIcon',
    'ForwardIcon',
    'ReplyIcon',
    'Forward2Icon',
    'Reply2Icon',
    'ArrowToDownLeftIcon',
    'ArrowToDownRightIcon',
    'ArrowToTopLeftIcon',
    'ArrowToTopRightIcon'
  ],
  likes: [
    'HeartIcon',
    'HeartAngleIcon',
    'HeartBrokenIcon',
    'HeartsIcon',
    'HeartLockIcon',
    'HeartUnLockIcon',
    'HeartShineIcon',
    'StarShineIcon',
    'StarIcon',
    'LikeIcon',
    'DislikeIcon',
    'MedalStarIcon',
    'MedalStarCircleIcon',
    'MedalStarSquareIcon',
    'MedalRibbonsStarIcon',
    'MedalRibbonStarIcon',
    'MedalRibbonIcon'
  ],
  foodKitchen: [
    'CupHotIcon',
    'CupIcon',
    'TeaCupIcon',
    'DonutIcon',
    'DonutBittenIcon',
    'BottleIcon',
    'CupPaperIcon',
    'RollingPinIcon',
    'CorkscrewIcon',
    'LadleIcon',
    'WhiskIcon',
    'ChefHatIcon',
    'ChefHatMinimalisticIcon',
    'ChefHatHeartIcon',
    'OvenMittsIcon',
    'OvenMittsMinimalisticIcon',
    'WineglassTriangleIcon',
    'WineglassIcon'
  ],
  designTools: [
    'PaletteIcon',
    'PaletteRoundIcon',
    'Palette2Icon',
    'LayersMinimalisticIcon',
    'LayersIcon',
    'RulerIcon',
    'RulerPenIcon',
    'RulerCrossPenIcon',
    'RulerAngularIcon',
    'FlipHorizontalIcon',
    'FlipVerticalIcon',
    'MirrorLeftIcon',
    'MirrorRightIcon',
    'PaintRulerIcon',
    'CropMinimalisticIcon',
    'CropIcon',
    'ColourTuningIcon',
    'RadialBlurIcon',
    'ThreeSquaresIcon',
    'FiltersIcon',
    'PipetteIcon',
    'AlignLeftIcon',
    'AlignRightIcon',
    'AlignBottomIcon',
    'AlignTopIcon',
    'AlignVerticalCenterIcon',
    'AlignHorizontalCenterIcon',
    'AlignHorizontalSpacingIcon',
    'AlignVerticalSpacingIcon'
  ],
  school: [
    'DiplomaIcon',
    'DiplomaVerifiedIcon',
    'CaseRoundIcon',
    'CaseIcon',
    'CaseRoundMinimalisticIcon',
    'CaseMinimalisticIcon',
    'BackpackIcon',
    'SquareAcademicCupIcon',
    'SquareAcademicCup2Icon',
    'NotebookMinimalisticIcon',
    'NotebookBookmarkIcon',
    'NotebookIcon',
    'NotebookSquareIcon',
    'BookIcon',
    'BookMinimalisticIcon',
    'BookBookmarkIcon',
    'BookBookmarkMinimalisticIcon',
    'Book2Icon',
    'PlusMinusIcon',
    'CalculatorMinimalisticIcon',
    'CalculatorIcon',
    'BookSquareIcon',
    'BookmarkIcon',
    'BookSquareMinimalisticIcon',
    'BookmarkCircleIcon',
    'BookmarkOpenedIcon',
    'PassportIcon',
    'PassportMinimalisticIcon',
    'SchoolDocumentIcon'
  ],
  natureTravel: [
    'FireIcon',
    'FlameIcon',
    'FireMinimalisticIcon',
    'FireSquareIcon',
    'BonfireIcon',
    'LeafIcon',
    'SuitcaseIcon',
    'SuitcaseTagIcon',
    'SuitcaseLinesIcon'
  ],
  users: [
    'UserRoundedIcon',
    'UsersRoundedIcon',
    'UsersTwoRoundedIcon',
    'UserCheckRoundedIcon',
    'UserCrossRoundedIcon',
    'UserPlusRoundedIcon',
    'UserMinusRoundedIcon',
    'UserBlockRoundedIcon',
    'UserSpeakRoundedIcon',
    'UserHeartRoundedIcon',
    'UserIcon',
    'UserCheckIcon',
    'UserPlusIcon',
    'UserCrossIcon',
    'UserMinusIcon',
    'UserBlockIcon',
    'UserSpeakIcon',
    'UserHeartIcon',
    'UserHandsIcon',
    'UserHandUpIcon',
    'UserCircleIcon',
    'UserIdIcon'
  ],
  shoppingECommerce: [
    'BagIcon',
    'BagCheckIcon',
    'BagCrossIcon',
    'Bag2Icon',
    'Bag3Icon',
    'Bag4Icon',
    'BagMusicIcon',
    'BagMusic2Icon',
    'BagSmileIcon',
    'Bag5Icon',
    'BagHeartIcon',
    'CartIcon',
    'Cart2Icon',
    'Cart3Icon',
    'Cart4Icon',
    'Cart5Icon',
    'CartLargeIcon',
    'CartLarge2Icon',
    'CartLargeMinimalisticIcon',
    'CartCheckIcon',
    'CartCrossIcon',
    'CartPlusIcon',
    'CartLarge3Icon',
    'CartLarge4Icon',
    'ShopIcon',
    'ShopMinimalisticIcon',
    'Shop2Icon'
  ],
  businessStatistic: [
    'PieChartIcon',
    'PieChart2Icon',
    'PieChart3Icon',
    'RoundGraphIcon',
    'GraphIcon',
    'GraphNewIcon',
    'GraphUpIcon',
    'GraphUpNewIcon',
    'GraphDownIcon',
    'GraphDownNewIcon',
    'PresentationGraphIcon',
    'DiagramUpIcon',
    'DiagramDownIcon',
    'ChartIcon',
    'Chart2Icon',
    'ChartSquareIcon',
    'ChartSquare2Icon',
    'CourseUpIcon',
    'CourseDownIcon'
  ],
  textFormatting: [
    'TextItalicIcon',
    'TextIcon',
    'TextCrossIcon',
    'TextUnderlineIcon',
    'TextBoldIcon',
    'EraserIcon',
    'TextItalicSquareIcon',
    'TextSquareIcon',
    'TextCrossSquareIcon',
    'TextUnderlineCrossIcon',
    'TextBoldCrossIcon',
    'EraserSquareIcon',
    'TextItalicCircleIcon',
    'TextCircleIcon',
    'TextCrossCircleIcon',
    'TextUnderlineCircleIcon',
    'TextBoldCircleIcon',
    'EraserCircleIcon',
    'TextSquare2Icon',
    'LinkIcon',
    'LinkBrokenIcon',
    'LinkMinimalisticIcon',
    'LinkMinimalistic2Icon',
    'LinkRoundIcon',
    'LinkRoundAngleIcon',
    'LinkCircleIcon',
    'LinkSquareIcon',
    'LinkBrokenMinimalisticIcon',
    'TextSelectionIcon',
    'ParagraphSpacingIcon',
    'BackspaceIcon',
    'TextFieldIcon',
    'TextFieldFocusIcon'
  ],
  buildingInfrastructure: ['CityIcon', 'BuildingsIcon', 'Buildings2Icon', 'Buildings3Icon', 'GarageIcon', 'HomeIcon', 'HospitalIcon'],
  settingsFineTuning: [
    'SettingsMinimalisticIcon',
    'SettingsIcon',
    'WidgetIcon',
    'Widget2Icon',
    'Widget3Icon',
    'Widget4Icon',
    'Widget5Icon',
    'Widget6Icon',
    'WidgetAddIcon',
    'TuningSquareIcon',
    'TuningSquare2Icon',
    'TuningIcon',
    'Tuning2Icon',
    'Tuning3Icon',
    'Tuning4Icon'
  ],
  networkItProgramming: [
    'WifiRouterRoundIcon',
    'WifiRouterMinimalisticIcon',
    'WifiRouterIcon',
    'ScreencastIcon',
    'Screencast2Icon',
    'StructureIcon',
    'CommandIcon',
    'TranslationIcon',
    'Translation2Icon',
    'BugMinimalisticIcon',
    'BugIcon',
    'UsbIcon',
    'UsbSquareIcon',
    'UsbCircleIcon',
    'CodeCircleIcon',
    'CodeSquareIcon',
    'CodeIcon',
    'Code2Icon',
    'SlashSquareIcon',
    'SlashCircleIcon',
    'ProgrammingIcon',
    'WindowFrameIcon',
    'SidebarCodeIcon',
    'SidebarIcon',
    'SidebarMinimalisticIcon',
    'StationIcon',
    'StationMinimalisticIcon',
    'HashtagIcon',
    'HashtagSquareIcon',
    'HashtagCircleIcon',
    'HashtagChatIcon'
  ],
  homeFurniture: [
    'ConditionerIcon',
    'Conditioner2Icon',
    'RemoteControllerIcon',
    'RemoteControllerMinimalisticIcon',
    'RemoteController2Icon',
    'WashingMachineMinimalisticIcon',
    'WashingMachineIcon',
    'SmartVacuumCleanerIcon',
    'SmartVacuumCleaner2Icon',
    'ArmchairIcon',
    'Armchair2Icon',
    'ChairIcon',
    'BarChairIcon',
    'Chair2Icon',
    'SofaIcon',
    'Sofa2Icon',
    'Sofa3Icon',
    'BedsideTableIcon',
    'BedsideTable2Icon',
    'BedsideTable3Icon',
    'BedsideTable4Icon',
    'ClosetIcon',
    'Closet2Icon',
    'BedIcon',
    'TrellisIcon',
    'SpeakerIcon',
    'SpeakerMinimalisticIcon',
    'MirrorIcon',
    'LampIcon',
    'FloorLampIcon',
    'FloorLampMinimalisticIcon',
    'BathIcon',
    'ChandelierIcon',
    'FridgeIcon',
    'VolumeKnobIcon'
  ],
  medicine: [
    'PillIcon',
    'PillsIcon',
    'Pills2Icon',
    'Pills3Icon',
    'AdhesivePlasterIcon',
    'AdhesivePlaster2Icon',
    'DNAIcon',
    'TestTubeIcon',
    'TestTubeMinimalisticIcon',
    'BoneIcon',
    'BoneCrackIcon',
    'BoneBrokenIcon',
    'BonesIcon',
    'SyringeIcon',
    'JarOfPillsIcon',
    'JarOfPills2Icon',
    'StethoscopeIcon',
    'BenzeneRingIcon',
    'ThermometerIcon',
    'DropperIcon',
    'Dropper2Icon',
    'Dropper3Icon',
    'DropperMinimalisticIcon',
    'DropperMinimalistic2Icon',
    'PulseIcon',
    'Pulse2Icon',
    'HeartPulseIcon',
    'HeartPulse2Icon',
    'BacteriaIcon',
    'MedicalKitIcon',
    'HealthIcon',
    'VirusIcon'
  ],
  call: [],
  security: [],
  essentialUi: [],
  list: [],
  hands: [],
  transportPartsService: [],
  time: [],
  search: [],
  sports: [],
  facesEmotionsStickers: [],
  folders: [],
  astronomy: [],
  files: [],
  weather: [],
  electronicDevices: [],
  money: [],
  videoAudioSound: [],
  mapLocation: [],
  arrows: [],
  messagesConversation: []
};

export const IconsListingMock = [
  {
    label: 'Notifications',
    components: IconUtils.sortByName(pathIcons['notificationIcons'], IconsSortMock.notifications)
  },
  {
    label: 'Notes - Documents',
    components: IconUtils.sortByName(pathIcons['noteDocumentIcons'], IconsSortMock.noteDocuments)
  },
  {
    label: 'Arrows Action',
    components: IconUtils.sortByName(pathIcons['arrowActionIcons'], IconsSortMock.arrowActions)
  },
  {
    label: 'Likes',
    components: IconUtils.sortByName(pathIcons['likeIcons'], IconsSortMock.likes)
  },
  {
    label: 'Food - KitChen',
    components: IconUtils.sortByName(pathIcons['foodKitchenIcons'], IconsSortMock.foodKitchen)
  },
  {
    label: 'Design - Tools',
    components: IconUtils.sortByName(pathIcons['designToolIcons'], IconsSortMock.designTools)
  },
  {
    label: 'School',
    components: IconUtils.sortByName(pathIcons['schoolIcons'], IconsSortMock.school)
  },
  {
    label: 'Nature - Travel',
    components: IconUtils.sortByName(pathIcons['natureTravelIcons'], IconsSortMock.natureTravel)
  },
  {
    label: 'User',
    components: IconUtils.sortByName(pathIcons['userIcons'], IconsSortMock.users)
  },
  {
    label: 'Shopping - ECommerce',
    components: IconUtils.sortByName(pathIcons['shoppingECommerceIcons'], IconsSortMock.shoppingECommerce)
  },
  {
    label: 'Business - Statistic',
    components: IconUtils.sortByName(pathIcons['businessStatisticIcons'], IconsSortMock.businessStatistic)
  },
  {
    label: 'Text formatting',
    components: IconUtils.sortByName(pathIcons['textFormattingIcons'], IconsSortMock.textFormatting)
  },
  {
    label: 'Building - Infrastructure',
    components: IconUtils.sortByName(pathIcons['buildingInfrastructureIcons'], IconsSortMock.buildingInfrastructure)
  },
  {
    label: 'Settings, Fine Tunning',
    components: IconUtils.sortByName(pathIcons['settingsFineTuningIcons'], IconsSortMock.settingsFineTuning)
  },
  {
    label: 'Settings, Fine Tunning',
    components: IconUtils.sortByName(pathIcons['networkItProgrammingIcons'], IconsSortMock.networkItProgramming)
  },
  {
    label: 'Home, Furniture',
    components: IconUtils.sortByName(pathIcons['homeFurnitureIcons'], IconsSortMock.homeFurniture)
  },
  {
    label: 'Medicine',
    components: IconUtils.sortByName(pathIcons['medicineIcons'], IconsSortMock.medicine)
  },
  {
    label: 'Call',
    components: IconUtils.sortByName(pathIcons['callIcons'], IconsSortMock.call)
  },
  {
    label: 'Security',
    components: IconUtils.sortByName(pathIcons['securityIcons'], IconsSortMock.security)
  },
  {
    label: 'Essential UI',
    components: IconUtils.sortByName(pathIcons['essentialUiIcons'], IconsSortMock.essentialUi)
  },
  {
    label: 'List',
    components: IconUtils.sortByName(pathIcons['listIcons'], IconsSortMock.list)
  },
  {
    label: 'Hands',
    components: IconUtils.sortByName(pathIcons['handsIcons'], IconsSortMock.hands)
  },
  {
    label: 'Transport - Parts - Service',
    components: IconUtils.sortByName(pathIcons['transportPartsServiceIcons'], IconsSortMock.transportPartsService)
  },
  {
    label: 'Time',
    components: IconUtils.sortByName(pathIcons['timeIcons'], IconsSortMock.time)
  },
  {
    label: 'Sports',
    components: IconUtils.sortByName(pathIcons['sportsIcons'], IconsSortMock.sports)
  },
  {
    label: 'Faces - Emotions - Stickers',
    components: IconUtils.sortByName(pathIcons['facesEmotionsStickersIcons'], IconsSortMock.facesEmotionsStickers)
  },
  {
    label: 'Folders',
    components: IconUtils.sortByName(pathIcons['foldersIcons'], IconsSortMock.folders)
  },
  {
    label: 'Astronomy',
    components: IconUtils.sortByName(pathIcons['astronomyIcons'], IconsSortMock.astronomy)
  },
  {
    label: 'Files',
    components: IconUtils.sortByName(pathIcons['filesIcons'], IconsSortMock.files)
  },
  {
    label: 'Weather',
    components: IconUtils.sortByName(pathIcons['weatherIcons'], IconsSortMock.weather)
  },
  {
    label: 'Electronic - Devices',
    components: IconUtils.sortByName(pathIcons['electronicDevicesIcons'], IconsSortMock.electronicDevices)
  },
  {
    label: 'Money',
    components: IconUtils.sortByName(pathIcons['moneyIcons'], IconsSortMock.money)
  },
  {
    label: 'Video - Audio - Sound',
    components: IconUtils.sortByName(pathIcons['videoAudioSoundIcons'], IconsSortMock.videoAudioSound)
  },
  {
    label: 'Map & Location',
    components: IconUtils.sortByName(pathIcons['mapLocationIcons'], IconsSortMock.mapLocation)
  },
  {
    label: 'Arrows',
    components: IconUtils.sortByName(pathIcons['arrowsIcons'], IconsSortMock.arrows)
  },
  {
    label: 'Messages - Conversation',
    components: IconUtils.sortByName(pathIcons['messagesConversationIcons'], IconsSortMock.messagesConversation)
  }
];
