name: MUITHEW-MONOREPOS RE-BUILD

on:
  pull_request:
    types: [opened, reopened]
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ignore cache
        run: yarn cache clean

      - name: Install serve
        run: yarn global add turbo gatsby remix

      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Build turbo packages
        run: yarn build --filter=./packages/**

      - name: Build storybooks
        run: yarn storybook:build

      - name: Turbo build apps
        run: yarn build --filter=./apps/**
