name: MUITHEW-MONOREPOS RE-BUILD

on:
  pull_request:
    types: [opened, reopened]
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Set up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Platform
        run: bun install --platform=linux --arch=x64

      - name: Install serve
        run: bun install turbo gatsby remix --global

      - name: Install dependencies
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Build turbo packages
        run: bun run --cwd packages build

      - name: Build storybooks
        run: bun run storybook:build

      - name: Turbo build apps
        run: bun run --cwd apps build
